// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type SteamParamDef struct {
	Key          string                `json:"key"`
	Label        string                `json:"label"`
	Type         string                `json:"type"`
	Options      pqtype.NullRawMessage `json:"options"`
	DefaultValue sql.NullString        `json:"default_value"`
	HelpText     sql.NullString        `json:"help_text"`
}

type TrackedItem struct {
	ID        int32           `json:"id"`
	Name      string          `json:"name"`
	Query     string          `json:"query"`
	Filters   json.RawMessage `json:"filters"`
	SentIds   []string        `json:"sent_ids"`
	Active    bool            `json:"active"`
	CreatedAt time.Time       `json:"created_at"`
}
